logging:
  level:
    root: warn
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.springframework.web.filter.CommonsRequestLoggingFilter: off
    de.agrirouter.middleware: trace
    com.dke.data.agrirouter: off

app:
  scheduled:
    connection-check: "0 */5 * * * *"
    fetching-and-confirming-existing-messages: "0 */15 * * * *"
    status-logging: "0 */5 * * * *"
    recipient-query: "0 */5 * * * *"
    empty-message-cache: "0 */15 * * * *"