logging:
  level:
    root: error

app:
  scheduled:
    connection-check: "0 */30 * * * *"
    fetching-and-confirming-existing-messages: "0 */15 * * * *"
    status-logging: "0 */15 * * * *"
    recipient-query: "0 */30 * * * *"